server:
  port: 8301
spring:
  application:
    name: config
  profiles:
    active: native #使用本地配置，要使用git存储改为git即可
  cloud:
    config:
      server:
        bootstrap: true
        native: #本地仓库存储
          search-locations: classpath:/config/{application}


