server:
  port: 8301
spring:
  application:
    name: config


  profiles:
    active: native #使用本地配置，要使用git存储改为git即可
  cloud:
    config:
      server:
        bootstrap: true
        native: #本地仓库存储
          search-locations: classpath:/config/{application}
        git: #Git仓库存储
          uri: https://github.com/rulingfeng/rlf-company/tree/shard_seata_redis_es/config
          username: 512387589@qq.com
          password: rlf13757139317
          clone-on-start: true
          search-paths: '{application}'



