server:
  port: 8082
spring:
  #正常的单库单表
#  datasource:
#    #type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://121.43.183.45:3306/order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#    username: root
#    password: shmliy

  #单库多表 具体看order-dev.yml
  main:
    allow-bean-definition-overriding: true

  #库名:order
  #
  #表名：order_main_1，order_main_2，order_main_3，order_main_4，order_detail_1，order_detail_2，order_detail_3，order_detail_4
#  CREATE TABLE `order_main_1` (
#  `id` bigint(20) NOT NULL AUTO_INCREMENT,
#  `order_id` bigint(11) DEFAULT NULL,
#  `order_no` bigint(20) DEFAULT NULL,
#  `user_id` bigint(20) DEFAULT NULL,
#  `cstatus` varchar(20) DEFAULT NULL,
#  `dynamic_time` bigint(11) DEFAULT NULL,
#  `create_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
#  PRIMARY KEY (`id`)
#  ) ENGINE=InnoDB AUTO_INCREMENT=2022 DEFAULT CHARSET=utf8mb4;
  #
  #  CREATE TABLE `order_detail_1` (
  #  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  #  `order_no` bigint(20) DEFAULT NULL,
  #  `user_id` bigint(20) DEFAULT NULL,
  #  `cstatus` varchar(20) DEFAULT NULL,
  #  `time` datetime DEFAULT NULL,
  #  PRIMARY KEY (`id`)
  #  ) ENGINE=InnoDB AUTO_INCREMENT=2007 DEFAULT CHARSET=utf8mb4;




mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

