
spring:
  datasource:
   # type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.43.183.45:3306/store?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: shmliy
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_seata_group
logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.rlf.dao: debug
    io:
      seata: info






