
spring:
  #单库单表
#  datasource:
#   # type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://121.43.183.45:3306/order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#    username: root
#    password: shmliy

  #单库多表
#  main:
#    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      #和下面的m1对应
      m1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: shmliy
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://121.43.183.45:3306/order?serverTimezone=GMT
        username: root
        #定义的库变量
      names: m1
    props:
      sql:
        show: true
    sharding:
      tables:
        #表名 重要！！！
        order_main:
          # 1..2 就是2张表  1..4就是  4张表
          actual-data-nodes: m1.order_main_$->{1..4}
          #            key-generator:
          #              column: cid
          #              type: SNOWFLAKE
          table-strategy:
            inline:
              algorithm-expression: order_main_$->{order_no % 4 + 1}
              sharding-column: order_no
        order_detail:
          # 1..2 就是2张表  1..4就是  4张表
          actual-data-nodes: m1.order_detail_$->{1..4}
          #            key-generator:
          #              column: cid
          #              type: SNOWFLAKE
          table-strategy:
            inline:
              algorithm-expression: order_detail_$->{order_no % 4 + 1}
              sharding-column: order_no


#seata:
#  enabled: true
#  tx-service-group: my_test_tx_group # 事务群组（可以每个应用独立取名，也可以使用相同的名字）
#  enable-auto-data-source-proxy: true
#  use-jdk-proxy: true
#  cloud:
#    alibaba:
#      seata:
#        tx-service-group: my_test_tx_group
seata:
  enabled: true
  tx-service-group: my_test_tx_group
  registry:
    type: eureka
    eureka:
      service-url: http://localhost:8761/eureka/
  client:
    support:
      spring:
        datasource-autoproxy: false
#    loadbalancer:
#      retry:
#        enabled: true

logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.rlf.dao: debug


order:
  type: asd




